"""Conservative cleanup helpers for files generated by older releases."""

from __future__ import annotations

import json
from pathlib import Path


def find_generated_sidecars(root: str | Path, *, limit: int = 10000) -> list[Path]:
    """Find only sidecars matching YT-Descargar's former schema."""

    library_root = Path(root).expanduser().resolve()
    if not library_root.is_dir():
        return []

    matches: list[Path] = []
    for candidate in library_root.rglob("*.info.json"):
        if len(matches) >= max(1, limit):
            break
        try:
            resolved = candidate.resolve()
            resolved.relative_to(library_root)
            if not resolved.is_file() or resolved.stat().st_size > 2 * 1024 * 1024:
                continue
            payload = json.loads(resolved.read_text(encoding="utf-8"))
            media_name = payload.get("media_file")
            if (
                payload.get("schema_version") != 1
                or not isinstance(payload.get("metadata"), dict)
                or not isinstance(media_name, str)
                or Path(media_name).name != media_name
                or resolved.name != f"{Path(media_name).stem}.info.json"
                or not (resolved.parent / media_name).is_file()
            ):
                continue
            matches.append(resolved)
        except (OSError, ValueError, json.JSONDecodeError):
            continue
    return matches


def remove_generated_sidecars(root: str | Path) -> list[Path]:
    """Remove sidecars positively identified as generated by this project."""

    removed: list[Path] = []
    for sidecar in find_generated_sidecars(root):
        try:
            sidecar.unlink()
            removed.append(sidecar)
        except OSError:
            continue
    return removed

